"""Added Quiz Models

Revision ID: 90eb342b9721
Revises: aebdf8939146
Create Date: 2026-04-13 15:53:38.693984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90eb342b9721'
down_revision: Union[str, Sequence[str], None] = 'aebdf8939146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('default_question_time', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_quiz_owner_id'), 'quiz', ['owner_id'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(length=1000), nullable=False),
    sa.Column('question_type', sa.Enum('SINGLE_ANSWER', 'MULTIPLE_ANSWER', name='questiontype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('answer_time', sa.Integer(), nullable=True),
    sa.Column('points_for_correct_answer', sa.Integer(), nullable=False),
    sa.Column('points_for_incorrect_answer', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'order_index', name='uq_question_quiz_order_index')
    )
    op.create_index(op.f('ix_question_quiz_id'), 'question', ['quiz_id'], unique=False)
    op.create_table('quizsession',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'LOBBY', 'LIVE', 'PAUSED', 'FINISHED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('join_code', sa.String(length=32), nullable=True),
    sa.Column('access_link_token', sa.String(length=255), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_quizsession_join_code'), 'quizsession', ['join_code'], unique=False)
    op.create_index(op.f('ix_quizsession_owner_id'), 'quizsession', ['owner_id'], unique=False)
    op.create_index(op.f('ix_quizsession_quiz_id'), 'quizsession', ['quiz_id'], unique=False)
    op.create_table('answeroption',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_answeroption_question_id'), 'answeroption', ['question_id'], unique=False)
    op.create_table('sessionparticipant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('guest_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('JOINED', 'READY', 'IN_PROGRESS', 'FINISHED', 'DISCONNECTED', name='participantstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_host', sa.BOOLEAN(), nullable=False),
    sa.CheckConstraint('\n            (\n                user_id IS NOT NULL\n                AND guest_name IS NULL\n                AND guest_token IS NULL\n            )\n            OR\n            (\n                user_id IS NULL\n                AND guest_name IS NOT NULL\n                AND guest_token IS NOT NULL\n            )\n            ', name='ck_sessionparticipant_user_or_guest'),
    sa.ForeignKeyConstraint(['session_id'], ['quizsession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sessionparticipant_session_id'), 'sessionparticipant', ['session_id'], unique=False)
    op.create_index('ix_sessionparticipant_session_id_host', 'sessionparticipant', ['session_id'], unique=False, postgresql_where=sa.text('is_host = true'))
    op.create_index(op.f('ix_sessionparticipant_user_id'), 'sessionparticipant', ['user_id'], unique=False)
    op.create_table('sessionquestionstate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CLOSED', name='sessionquestionstatus'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quizsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_sessionquestionstate_session_question')
    )
    op.create_index(op.f('ix_sessionquestionstate_question_id'), 'sessionquestionstate', ['question_id'], unique=False)
    op.create_index(op.f('ix_sessionquestionstate_session_id'), 'sessionquestionstate', ['session_id'], unique=False)
    op.create_table('participantanswer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answered_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['sessionparticipant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quizsession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', 'question_id', name='uq_participantanswer_session_participant_question')
    )
    op.create_index(op.f('ix_participantanswer_participant_id'), 'participantanswer', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participantanswer_question_id'), 'participantanswer', ['question_id'], unique=False)
    op.create_index(op.f('ix_participantanswer_session_id'), 'participantanswer', ['session_id'], unique=False)
    op.create_table('participant_answer_option',
    sa.Column('participant_answer_id', sa.UUID(), nullable=False),
    sa.Column('answer_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_option_id'], ['answeroption.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_answer_id'], ['participantanswer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_answer_id', 'answer_option_id'),
    sa.UniqueConstraint('participant_answer_id', 'answer_option_id', name='uq_participantansweroption_answer_option')
    )
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('participant_answer_option')
    op.drop_index(op.f('ix_participantanswer_session_id'), table_name='participantanswer')
    op.drop_index(op.f('ix_participantanswer_question_id'), table_name='participantanswer')
    op.drop_index(op.f('ix_participantanswer_participant_id'), table_name='participantanswer')
    op.drop_table('participantanswer')
    op.drop_index(op.f('ix_sessionquestionstate_session_id'), table_name='sessionquestionstate')
    op.drop_index(op.f('ix_sessionquestionstate_question_id'), table_name='sessionquestionstate')
    op.drop_table('sessionquestionstate')
    op.drop_index(op.f('ix_sessionparticipant_user_id'), table_name='sessionparticipant')
    op.drop_index('ix_sessionparticipant_session_id_host', table_name='sessionparticipant', postgresql_where=sa.text('is_host = true'))
    op.drop_index(op.f('ix_sessionparticipant_session_id'), table_name='sessionparticipant')
    op.drop_table('sessionparticipant')
    op.drop_index(op.f('ix_answeroption_question_id'), table_name='answeroption')
    op.drop_table('answeroption')
    op.drop_index(op.f('ix_quizsession_quiz_id'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_owner_id'), table_name='quizsession')
    op.drop_index(op.f('ix_quizsession_join_code'), table_name='quizsession')
    op.drop_table('quizsession')
    op.drop_index(op.f('ix_question_quiz_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_quiz_owner_id'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
